version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: backend-service
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cs308db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1215.Faruk
    volumes:
      - ./invoices:/app/invoices

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1215.Faruk
      MYSQL_DATABASE: cs308db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: cs308-frontend-local     # ✅ Frontend local image
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: